# Use the official NGINX image as the base image
FROM nginx:latest

# Copy custom NGINX config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for incoming traffic
EXPOSE 80

# CMD to start NGINX and keep it running
CMD ["nginx", "-g", "daemon off;"]